### ISSUE TITLE
JSON Manifest Issues:

### ISSUE THREAD

**Issue by beanpole135** [trueos/trueos#105]
1. The "dist-packages" list is not getting properly expanded by the contents of the "auto-install-packages" list. This means that the entire auto-install-packages list has to be duplicated into the dist-packages list at the moment.
2. Same as 1, but for the "iso-install-packages" list. This also needs to be duplicated into the dist-packages list at the moment for a "make release" to succeeed. The "iso-install-packages" list should actually be using the system package repository and not the package repository on the ISO file though - that way packages can be installed into the ISO which are not going to be installed *from* the ISO into the live system.

**Comment by darkfiberiru** [comment]
When you say system you mean pkg repo from this build though right not the actual global system repo correct?

**Comment by beanpole135** [comment]
Yes, for part 2 the ISO install packages need to be fetched from the just-built package repo from the previous steps - not tied to the package repos on the build system itself.
