### ISSUE TITLE
TrueOS18.03 pc-updatemanager fails to inform user that version 18.06 is available.

### ISSUE THREAD

**Issue by mrT55** [trueos/trueos#129]
```
pkg --version
1.10.5
```

pc-updatemanager-201711181009

```
boot environment now (N) … 12.0-CURRENT-201807011525 NR 2018-07-01
OS git branch ……………………………………………………………………………………… trueos-stable-18.03
OS git revision ………………………………………………………………………………… fa797a5a3
OS kernel build time ………………………………………………………… Mon 2018 Mar 26 00:24:47 UTC
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… STABLE
TrueOS version …………………………… TrueOS-Desktop-201803131015
```

```
The following was ran on 08/03/2018 at 09.52p Eastern Time
# pc-updatemanager confcheck
    Boot-strapping updater...OK

# pc-updatemanager syncconf
   Boot-strapping updater...OK

# pc-updatemanager check
   Boot-strapping updater...OK
   No updates available for 12.0-CURRENT!

# pc-updatemanager pkgcheck
    Boot-strapping updater...OK
    Updating the pkg database...
    All packages are up to date!
```
---> and yet it is unable to find nor tell me that version 18.06 is available.
Note: I did stumble across: http://pkg.trueos.org/iso/18.06/
         However, with the above message 'No updates available...' why would I be looking 
         for an update?

**Comment by Mrt134** [comment]
This is a reflection of the reorganisation of the TrueOS project. The 18.06 TrueOS version is a server only installation with very limited packages and no default graphical desktop environment. The planned update/upgrade path for 18.03 is the first release of Project Trident, as this project is a smooth continuation of the 18.03 experience. See https://www.trueos.org/blog/trueosdownstream/ for more details.

The first release of Project Trident is expected in mid to late August. You can see updates on Trident at the website: http://project-trident.org/
