### ISSUE TITLE
Unable to install TrueOS Desktop

### ISSUE THREAD

**Issue by outpaddling** [trueos/trueos#188]
Trying to install trueos-desktop from TrueOS-Desktop-18.03-x64-USB.img leads to "Can't load geom_uzip:", at which point the computer freezes.

TrueOS-Stable-x64-18.06.iso installs fine, but "pkg install trueos-desktop" results in

FreeBSD-runtime-12.0-s20180802163734  conflicts with trueos-core-201807060938

Problematic file: /boot/brand-trueos-4th

**Comment by jgroenveld** [comment]
```
Does Trident RC2 boot on your h/w?
<URL:http://www.project-trident.org/download/>
John
groenveld@acm.org
```

**Comment by outpaddling** [comment]
Yes, the only install issue with Trident is it hangs for several minutes right after switching to graphics mode.  I see "Starting the Trident installer", then a garbled screen for the better part of a minute, then a blank screen for several minutes.

Post-install, I could not run AppCafe' or Control Panel.  Got a popup saying syadm is not running.  Trying trueos-update now from a terminal to see if it helps.

You might want to advertise Trident on the TrueOS downloads page for people looking for a Desktop OS.  Right now, a NOOB looking to try out PC-BSD or TrueOS desktop might get the impression that the desktop project is dead.  I'd hate to see potential satisfied users lost in the confusion of all the reorganization happening lately.

**Comment by miwi-fbsd** [comment]
http://www.project-trident.org is the Desktop Project now.
