### ISSUE TITLE
each base package installes pkg new.

### ISSUE THREAD

**Issue by miwi-fbsd** [trueos/trueos#214]
Happened since upgrade to 13,

> pkg-static: Warning: Major OS version upgrade detected.  Running "pkg-static install -f pkg" recommended
> DBG(1)[86751]> want to get an advisory lock on a database
> DBG(1)[86751]> Binary> loading /var/cache/trueos-upgrade/pkg-1.10.5_5-2f2284bc62.txz
> DBG(1)[86751]> Binary> loading /var/cache/trueos-upgrade/TrueOS-bhyve-13.0.2018.11.10-06.59.09-65a09bfc38.txz
> DBG(1)[86751]> Binary> loading /var/cache/trueos-upgrade/TrueOS-libvmmapi-13.0.2018.11.10-06.59.09-926850ce09.txz
> Checking integrity...DBG(1)[86751]> check integrity for 3 items added
>  done (0 conflicting)
> The following 3 package(s) will be affected (of 0 checked):
> 
> New packages to be INSTALLED:
> 	TrueOS-bhyve: 13.0.2018.11.10-06.59.09 [TrueOS-base]
> 	TrueOS-libvmmapi: 13.0.2018.11.10-06.59.09 [TrueOS-base]
> 
> Installed packages to be REINSTALLED:
> 	pkg-1.10.5_5 [TrueOS-base]
> 
> Number of packages to be installed: 2
> Number of packages to be reinstalled: 1
> DBG(1)[86751]> want to upgrade advisory to exclusive lock
> [1/3] Reinstalling pkg-1.10.5_5...
> [1/3] Extracting pkg-1.10.5_5: .......... done
> DBG(1)[86751]> Cleaning up old version
> [2/3] Installing TrueOS-bhyve-13.0.2018.11.10-06.59.09...
> [2/3] Extracting TrueOS-bhyve-13.0.2018.11.10-06.59.09: ...... done
> [3/3] Installing TrueOS-libvmmapi-13.0.2018.11.10-06.59.09...
> [3/3] Extracting TrueOS-libvmmapi-13.0.2018.11.10-06.59.09: . done
> DBG(1)[86751]> release an exclusive lock on a database
> DBG(1)[86751]> release an advisory lock on a database
> Installing: TrueOS-bhyve-debug
> DBG(1)[89289]> pkg initialized
> pkg-static: Warning: Major OS version upgrade detected.  Running "pkg-static install -f pkg" recommended
> DBG(1)[89289]> want to get an advisory lock on a database
> DBG(1)[89289]> Binary> loading /var/cache/trueos-upgrade/pkg-1.10.5_5-2f2284bc62.txz
> DBG(1)[89289]> Binary> loading /var/cache/trueos-upgrade/TrueOS-bhyve-debug-13.0.2018.11.10-06.59.09-de35f7872c.txz
> Checking integrity...DBG(1)[89289]> check integrity for 2 items added
>  done (0 conflicting)
> The following 2 package(s) will be affected (of 0 checked):
> 
> New packages to be INSTALLED:
> 	TrueOS-bhyve-debug: 13.0.2018.11.10-06.59.09 [TrueOS-base]
> 
> Installed packages to be REINSTALLED:
> 	pkg-1.10.5_5 [TrueOS-base]
> 
> Number of packages to be installed: 1
> Number of packages to be reinstalled: 1
> DBG(1)[89289]> want to upgrade advisory to exclusive lock
> [1/2] Reinstalling pkg-1.10.5_5...
> [1/2] Extracting pkg-1.10.5_5: .......... done
> DBG(1)[89289]> Cleaning up old version
> [2/2] Installing TrueOS-bhyve-debug-13.0.2018.11.10-06.59.09...
> [2/2] Extracting TrueOS-bhyve-debug-13.0.2018.11.10-06.59.09: ... done
> DBG(1)[89289]> release an exclusive lock on a database
> DBG(1)[89289]> release an advisory lock on a database
> Installing: TrueOS-binutils
> DBG(1)[90554]> pkg initialized
> pkg-static: Warning: Major OS version upgrade detected.  Running "pkg-static install -f pkg" recommended
> DBG(1)[90554]> want to get an advisory lock on a database
> DBG(1)[90554]> Binary> loading /var/cache/trueos-upgrade/pkg-1.10.5_5-2f2284bc62.txz
> DBG(1)[90554]> Binary> loading /var/cache/trueos-upgrade/TrueOS-binutils-13.0.2018.11.10-06.59.09-7d9f618919.txz
> Checking integrity...DBG(1)[90554]> check integrity for 2 items added
>  done (0 conflicting)
> The following 2 package(s) will be affected (of 0 checked):
> 
> New packages to be INSTALLED:
> 	TrueOS-binutils: 13.0.2018.11.10-06.59.09 [TrueOS-base]
> 
> Installed packages to be REINSTALLED:
> 	pkg-1.10.5_5 [TrueOS-base]
> 
> Number of packages to be installed: 1
> Number of packages to be reinstalled: 1
> 
> The process will require 5 MiB more space.
> DBG(1)[90554]> want to upgrade advisory to exclusive lock
> [1/2] Reinstalling pkg-1.10.5_5...
> [1/2] Extracting pkg-1.10.5_5: .......... done
> DBG(1)[90554]> Cleaning up old version
> [2/2] Installing TrueOS-binutils-13.0.2018.11.10-06.59.09...
> [2/2] Extracting TrueOS-binutils-13.0.2018.11.10-06.59.09: .......... done
> DBG(1)[90554]> release an exclusive lock on a database
> DBG(1)[90554]> release an advisory lock on a database
> Installing: TrueOS-binutils-debug
> DBG(1)[91704]> pkg initialized
> pkg-static: Warning: Major OS version upgrade detected.  Running "pkg-static install -f pkg" recommended
> DBG(1)[91704]> want to get an advisory lock on a database
> DBG(1)[91704]> Binary> loading /var/cache/trueos-upgrade/pkg-1.10.5_5-2f2284bc62.txz
> DBG(1)[91704]> Binary> loading /var/cache/trueos-upgrade/TrueOS-binutils-debug-13.0.2018.11.10-06.59.09-362aaab00e.txz
> Checking integrity...DBG(1)[91704]> check integrity for 2 items added
>  done (0 conflicting)
> The following 2 package(s) will be affected (of 0 checked):
> 
> New packages to be INSTALLED:
> 	TrueOS-binutils-debug: 13.0.2018.11.10-06.59.09 [TrueOS-base]
> 
> Installed packages to be REINSTALLED:
> 	pkg-1.10.5_5 [TrueOS-base]
> 
> Number of packages to be installed: 1
> Number of packages to be reinstalled: 1
> 
> The process will require 15 MiB more space.
> DBG(1)[91704]> want to upgrade advisory to exclusive lock
> [1/2] Reinstalling pkg-1.10.5_5...
> [1/2] Extracting pkg-1.10.5_5: .......... done
> DBG(1)[91704]> Cleaning up old version
> [2/2] Installing TrueOS-binutils-debug-13.0.2018.11.10-06.59.09...
> [2/2] Extracting TrueOS-binutils-debug-13.0.2018.11.10-06.59.09: ... done
> DBG(1)[91704]> release an exclusive lock on a database
> DBG(1)[91704]> release an advisory lock on a database
> Installing: TrueOS-bsdinstall
> DBG(1)[92984]> pkg initialized
> pkg-static: Warning: Major OS version upgrade detected.  Running "pkg-static install -f pkg" recommended
> DBG(1)[92984]> want to get an advisory lock on a database
> DBG(1)[92984]> Binary> loading /var/cache/trueos-upgrade/pkg-1.10.5_5-2f2284bc62.txz
> DBG(1)[92984]> Binary> loading /var/cache/trueos-upgrade/TrueOS-bsdinstall-13.0.2018.11.10-06.59.09-15af7aeb45.txz
> Checking integrity...DBG(1)[92984]> check integrity for 2 items added
>  done (0 conflicting)
> The following 2 package(s) will be affected (of 0 checked):
> 
> New packages to be INSTALLED:
> 	TrueOS-bsdinstall: 13.0.2018.11.10-06.59.09 [TrueOS-base]
> 
> Installed packages to be REINSTALLED:
> 	pkg-1.10.5_5 [TrueOS-base]
> 
> Number of packages to be installed: 1
> Number of packages to be reinstalled: 1
> DBG(1)[92984]> want to upgrade advisory to exclusive lock
> [1/2] Reinstalling pkg-1.10.5_5...
> [1/2] Extracting pkg-1.10.5_5: .......... done
> DBG(1)[92984]> Cleaning up old version
> [2/2] Installing TrueOS-bsdinstall-13.0.2018.11.10-06.59.09...
> [2/2] Extracting TrueOS-bsdinstall-13.0.2018.11.10-06.59.09: .......... done
> DBG(1)[92984]> release an exclusive lock on a database
> DBG(1)[92984]> release an advisory lock on a database
> Installing: TrueOS-bsdinstall-debug
> DBG(1)[94660]> pkg initialized
> pkg-static: Warning: Major OS version upgrade detected.  Running "pkg-static install -f pkg" recommended
> DBG(1)[94660]> want to get an advisory lock on a database
> DBG(1)[94660]> Binary> loading /var/cache/trueos-upgrade/pkg-1.10.5_5-2f2284bc62.txz
> DBG(1)[94660]> Binary> loading /var/cache/trueos-upgrade/TrueOS-bsdinstall-debug-13.0.2018.11.10-06.59.09-80a8e173b6.txz
> Checking integrity...DBG(1)[94660]> check integrity for 2 items added
>  done (0 conflicting)
> The following 2 package(s) will be affected (of 0 checked):
> 
> New packages to be INSTALLED:
> 	TrueOS-bsdinstall-debug: 13.0.2018.11.10-06.59.09 [TrueOS-base]
> 
> Installed packages to be REINSTALLED:
> 	pkg-1.10.5_5 [TrueOS-base]
> 
> Number of packages to be installed: 1
> Number of packages to be reinstalled: 1
> DBG(1)[94660]> want to upgrade advisory to exclusive lock
> [1/2] Reinstalling pkg-1.10.5_5...
> [1/2] Extracting pkg-1.10.5_5: .......... done
> DBG(1)[94660]> Cleaning up old version
> [2/2] Installing TrueOS-bsdinstall-debug-13.0.2018.11.10-06.59.09...
> [2/2] Extracting TrueOS-bsdinstall-debug-13.0.2018.11.10-06.59.09: ... done
> DBG(1)[94660]> release an exclusive lock on a database
> DBG(1)[94660]> release an advisory lock on a database
> Installing: TrueOS-bsnmp
> DBG(1)[95932]> pkg initialized
> pkg-static: Warning: Major OS version upgrade detected.  Running "pkg-static install -f pkg" recommended
> DBG(1)[95932]> want to get an advisory lock on a database
> DBG(1)[95932]> Binary> loading /var/cache/trueos-upgrade/pkg-1.10.5_5-2f2284bc62.txz
> DBG(1)[95932]> Binary> loading /var/cache/trueos-upgrade/TrueOS-bsnmp-13.0.2018.11.10-06.59.09-757116dbc4.txz
> Checking integrity...DBG(1)[95932]> check integrity for 2 items added
>  done (0 conflicting)
> The following 2 package(s) will be affected (of 0 checked):
> 
> New packages to be INSTALLED:
> 	TrueOS-bsnmp: 13.0.2018.11.10-06.59.09 [TrueOS-base]
> 
> Installed packages to be REINSTALLED:
> 	pkg-1.10.5_5 [TrueOS-base]
> 
> Number of packages to be installed: 1
> Number of packages to be reinstalled: 1

**Comment by kmoore134** [comment]
I'm not seeing this here locally anymore. If you can reproduce with later sysup, please re-open.

**Comment by RodMyers** [comment]
here on latest update

**Comment by miwi-fbsd** [comment]
Fixed with sysup.
