### ISSUE TITLE
Snapshot does not build - sendmail /etc/mail/aliases error

### ISSUE THREAD

**Issue by jimbygh** [trueos/trueos#226]
Steps to reproduce:
1. Downloaded snapshot #180 from https://builds.ixsystems.com/jenkins/job/TrueOS%20-%20Snapshot%20Build/180/artifact/artifacts/disc1.iso
2. Installed on bare metal.  Install completed without errors.
3. Downloaded src.txz and ports.txz from same site and installed in /usr/src and /usr/ports respectively.
4. pkg install llvm60
5. Ran compiler-bootstrap llvm60  (I had difficulty with this step, but eventually managed to get it done.)
6. pkg install poudriere  (required to build src and ports)
7. pkg install git  (also required)
6.  cd /usr/src
    make buildworld buildkernel

Buildworld fails on building usr.sbin/sendmail

make[5]: don't know how to make  /etc/mail/aliases.  Stop

**Comment by jimbygh** [comment]
Cause seems to be that the snapshot base has no files in /etc/mail.

I populated /etc/mail/aliases and /etc/mail/sendmail.cf  with copies from a working system and started a rebuild.

**Comment by jimbygh** [comment]
ok, that seems to do the trick.  just populate the /etc/mail  directory with an alias file and a sendmail.cf file.

the build  completed successfully.  i was able to make all packages and generate a release as well.

we'll need a trueos developer to add the alias and sendmail.cf to /etc/mail  in the base images used for snapshots and the upcoming release.

Jim B.

**Comment by jimbygh** [comment]
Also - be aware that the build scripts for the .iso do not populate /etc/mail.

So, in addition to adding the aliases file and sendmail.cf to /etc/mail in base, you will have to ensure that those files get copied to the staging area prior to making the .iso.

--Jim B.

**Comment by jimbygh** [comment]
wellll .....  hang on.

a fresh install, with the steps above and including only /etc/mail/aliases and /etc/mail/sendmail.cfg  did not complete a full  make buildworld.

the build stops on the same step as noted in the first note on this issue.

I'm retrying with another complete reinstall, fresh download, and a full set of files in /etc/mail
including
```
-rw-r--r--   1 root  wheel     558 Dec  9  2017 access.sample                                                                                                                                        
-rw-r--r--   1 root  wheel    1624 Dec  9  2017 aliases                                                                                                                                              
-rw-r-----   1 root  wheel  131072 Dec 24  2017 aliases.db                                                                                                                                           
-rw-r--r--   1 root  wheel   58664 Dec  9  2017 freebsd.cf                                                                                                                                           
-rw-r--r--   1 root  wheel    4460 Dec  9  2017 freebsd.mc                                                                                                                                           
-r--r--r--   1 root  wheel   40998 Dec  9  2017 freebsd.submit.cf                                                                                                                                    
-r--r--r--   1 root  wheel     814 Dec  9  2017 freebsd.submit.mc                                                                                                                                    
-r--r--r--   1 root  wheel    5659 Dec  9  2017 helpfile                                                                                                                                             
-rw-r--r--   1 root  wheel     334 Dec  9  2017 mailer.conf                                                                                                                                          
-rw-r--r--   1 root  wheel     171 Dec  9  2017 mailertable.sample                                                                                                                                   
-rw-r--r--   1 root  wheel    6751 Dec  9  2017 Makefile
-rw-r--r--   1 root  wheel    2834 Dec  9  2017 README
-rw-r--r--   1 root  wheel   58664 Dec  9  2017 sendmail.cf
-r--r--r--   1 root  wheel   40998 Dec  9  2017 submit.cf
-rw-r--r--   1 root  wheel     498 Dec  9  2017 virtusertable.sample
```

**Comment by kmoore134** [comment]
Interesting, especially since it shouldn't be using files out of /etc/mail for buildworld at all.. Those should be coming from /usr/src/ right? Can you attach the full buildworld log?

**Comment by jimbygh** [comment]
The Makefile in /usr/src/usr.sbin/sendmail/mail has the variable (line 89)
```
SENDMAIL_ALIASES?=    /etc/mail/aliases
```

which is used in a macro at lines 175-179:
```
.for _f in ${SENDMAIL_ALIASES}
${_f}.db:  ${_f}
        ${SENDMAIL} -bi -OAliasFile=${.ALLSRC}
        chmod ${SENDMAIL_MAP_PERMS| ${.TARGET}
.endfor
```
the reference target is at line 219:
```
aliases:  ${SENDMAIL_ALIASES:%=%.db|
```
I will have to start another build to attach a buildworld log.

**Comment by jimbygh** [comment]
Quick note - I did a make buildworld and buildkernel  with the files listed above in /etc/mail.

The build completed successfully.
