### ISSUE TITLE
Intel IGB Driver missing

### ISSUE THREAD

**Issue by revhelix** [trueos/trueos#256]
https://www.freebsd.org/cgi/man.cgi?igb(4)

This driver is missing from the kernel. 
It really should be in. 

Has this been removed from FreeBSD 13? not ready?

I downloaded the source and tried to add it into a kernel configuration and it complained that there was no supporting files for the device.

Cheers,

Mark.

**Comment by amotin** [comment]
igb(4) driver was merged with em(4).

**Comment by revhelix** [comment]
ok, well, there are issues.

The kernel debug msgs made reference to igb, then proceeded to crash the system.

The system thankfully rebooted, and completed.

Quad port card is not visible to the system.

**Comment by revhelix** [comment]
And yes, this is on 18.12.

**Comment by revhelix** [comment]
From dmesg:

igb0: <Intel(R) PRO/1000 PCI-Express Network Driver> mem 0xd1180000-0xd11fffff,0xd1104000-0xd1107fff irq 33 at device 0.0 numa-domain 1 on pci10
igb0: attach_pre capping queues at 8
igb0: using 1024 tx descriptors and 1024 rx descriptors
igb0: msix_init qsets capped at 8
igb0: pxm cpus: 0 queue msgs: 9 admincnt: 1
igb0: using 0 rx queues 0 tx queues 
igb0: Using MSIX interrupts with 1 vectors
igb0: allocated for 0 tx_queues
igb0: allocated for 0 rx_queues
igb0: failed to allocate IRQ for rid 0, name irq0.
igb0: iflib_legacy_setup failed 12
device_attach: igb0 attach returned 12
igb0: <Intel(R) PRO/1000 PCI-Express Network Driver> mem 0xd1280000-0xd12fffff,0xd110c000-0xd110ffff irq 31 at device 0.1 numa-domain 1 on pci10
igb0: attach_pre capping queues at 8
igb0: using 1024 tx descriptors and 1024 rx descriptors
igb0: msix_init qsets capped at 8
igb0: pxm cpus: 0 queue msgs: 9 admincnt: 1
igb0: using 0 rx queues 0 tx queues 
igb0: Using MSIX interrupts with 1 vectors
igb0: allocated for 0 tx_queues
igb0: allocated for 0 rx_queues
igb0: failed to allocate IRQ for rid 0, name irq0.
igb0: iflib_legacy_setup failed 12
device_attach: igb0 attach returned 12
igb0: <Intel(R) PRO/1000 PCI-Express Network Driver> mem 0xd1380000-0xd13fffff,0xd1114000-0xd1117fff irq 46 at device 0.2 numa-domain 1 on pci10
igb0: attach_pre capping queues at 8
igb0: using 1024 tx descriptors and 1024 rx descriptors
igb0: msix_init qsets capped at 8
igb0: pxm cpus: 0 queue msgs: 9 admincnt: 1
igb0: using 0 rx queues 0 tx queues 
igb0: Using MSIX interrupts with 1 vectors
igb0: allocated for 0 tx_queues
igb0: allocated for 0 rx_queues
igb0: failed to allocate IRQ for rid 0, name irq0.
igb0: iflib_legacy_setup failed 12
device_attach: igb0 attach returned 12
igb0: <Intel(R) PRO/1000 PCI-Express Network Driver> mem 0xd1480000-0xd14fffff,0xd111c000-0xd111ffff irq 45 at device 0.3 numa-domain 1 on pci10
igb0: attach_pre capping queues at 8
igb0: using 1024 tx descriptors and 1024 rx descriptors
igb0: msix_init qsets capped at 8
igb0: pxm cpus: 0 queue msgs: 9 admincnt: 1
igb0: using 0 rx queues 0 tx queues 
igb0: Using MSIX interrupts with 1 vectors
igb0: allocated for 0 tx_queues
igb0: allocated for 0 rx_queues
igb0: failed to allocate IRQ for rid 0, name irq0.
igb0: iflib_legacy_setup failed 12

**Comment by mattmacy** [comment]
Could you provide the full dmesg somewhere

**Comment by kmoore134** [comment]
Closing this due to lack of feedback.
