### ISSUE TITLE
make package dont respect custom kernel

### ISSUE THREAD

**Issue by miwi-fbsd** [trueos/trueos#260]
While trying to package a custom kernel below things are happened.

`--------------------------------------------------------------
>>> Installing everything completed on Fri Dec 21 11:53:50 +08 2018
--------------------------------------------------------------
--- unlink-packages ---
--- _repodir ---
--- create-packages-world ---
--- create-packages-kernel ---
--- create-packages-world ---
Using TRUEOS_MANIFEST: /root/jenkins/workspace/TrueOS-i3wm/release/manifests/trueos-snapshot-i3.json
--- create-packages-kernel ---
Using TRUEOS_MANIFEST: /root/jenkins/workspace/TrueOS-i3wm/release/manifests/trueos-snapshot-i3.json
--- create-packages-world ---
Using TRUEOS_MANIFEST: /root/jenkins/workspace/TrueOS-i3wm/release/manifests/trueos-snapshot-i3.json
--- create-packages-kernel ---
Using TRUEOS_MANIFEST: /root/jenkins/workspace/TrueOS-i3wm/release/manifests/trueos-snapshot-i3.json
--- create-packages-world ---
--- create-world-packages ---
--- create-packages-kernel ---
--- create-kernel-packages-flavor-debug ---
--- create-kernel-packages-flavor-default ---
--- create-kernel-packages-flavor-debug ---
===> Creating TrueOS-kernel-i3-debug-13.0.20181221035318
FreeBSD I3 kernel -debugrUnversioned directory
--- create-kernel-packages-flavor-default ---
===> Creating TrueOS-kernel-i3-13.0.20181221035318
FreeBSD I3 kernel rUnversioned directory
====> Calculating plist checksum for kernel.I3
--- create-kernel-packages-flavor-debug ---
====> Calculating plist checksum for kernel.I3-debug
sha256: /usr/obj/usr/trueos-src/amd64.amd64/kernelstage/kernel/kernel.I3-debug.plist: No such file or directory
/usr/trueos-src/release/packages/build-checksum.sh: cannot open /usr/obj/usr/trueos-src/amd64.amd64/kernelstage/kernel/kernel.I3-debug.plist: No such file or directory
=====> Building fresh package for kernel-i3-debug
pkg-static: Unable to open plist file: /usr/obj/usr/trueos-src/amd64.amd64/kernelstage/kernel/kernel.I3-debug.plist
*** [create-kernel-packages-flavor-debug] Error code 70

make[4]: stopped in /usr/trueos-src
--- create-packages-world ---
(mkdir -p /usr/obj/usr/trueos-src/amd64.amd64/worldstage/var/db || true) ;  echo "@dir(root,wheel,0755,) /var/db" >> /usr/obj/usr/trueos-src/amd64.amd64/worldstage/runtime.plist ;  echo "Saving TrueOS Manifest" ;  cp /root/jenkins/workspace/TrueOS-i3wm/release/manifests/trueos-snapshot-i3.json /usr/obj/usr/trueos-src/amd64.amd64/worldstage/var/db/trueos-manifest.json ;  echo "@(root,wheel,0444,) /var/db/trueos-manifest.json" >> /usr/obj/usr/trueos-src/amd64.amd64/worldstage/runtime.plist
Saving TrueOS Manifest`

**Comment by kmoore134** [comment]
Ok, added patch that should fix the missing .plist file. Please re-open if still an issue.
