### ISSUE TITLE
jenkins manifest allow custom kernel definition

### ISSUE THREAD

**Issue by miwi-fbsd** [trueos/trueos#270]
Right now we have to hard code it to the make targets, it would be better to have a manifest definition for that, as example for the ZOL build you have deep debug flags enabled, I dont need these in the normal snapshot builds, or for the desktop builds at all, so we have the ability to define our own kernels, @beanpole135  have a nice implementation for that.

**Comment by beanpole135** [comment]
What @miwi-fbsd  is referring to is the FreeBSD kernel config option that Project Trident exposes via the JSON manifest in the build-distro.sh script (lines 41-45):
https://github.com/project-trident/trident-build/blob/649dc5735ab7c104c07e5d9f12019770e245409c/build-distro.sh#L41

**Comment by miwi-fbsd** [comment]
Also when we hardcode KERNCONF we are getting null-generic-*-date back, pkg is not able to handle this, and we are not passing KERNCONF properly to make installkernel target https://github.com/trueos/trueos/blob/trueos-master/release/Makefile#L222

**Comment by miwi-fbsd** [comment]
Fixed with the new build system
