### ISSUE TITLE
xfce4-screenshooter package is missing

### ISSUE THREAD

**Issue by robertwolter** [trueos/trueos#274]
There is xfce4-screenshooter-plugin, but no xfce4-screenshooter in the repo.

**Comment by miwi-fbsd** [comment]
Hi Robert,

this is on Trueos or on Trident ?

**Comment by robertwolter** [comment]
Both and on FreeBSD as well. It seems to be a general FreeBSD problem.

**Comment by miwi-fbsd** [comment]
For Trident https://pkg.project-trident.org/pkg/release/FreeBSD%3A13%3Aamd64/latest/All/xfce4-screenshooter-plugin-1.9.3.txz the package is here,

for TrueOS:
https://pkg.trueos.org/pkg/unstable/FreeBSD%3A13%3Aamd64/latest/All/xfce4-screenshooter-plugin-1.9.3.txz 

Could u please give me the output of "pkg search xfce"

Thanks.

**Comment by robertwolter** [comment]
Ok, I searched for it and installed "xfce4-screenshooter-plugin". This works correctly. But the "normal" package "xfce4-screenshooter" is missing.
![screenshot-2019-01-12-21-26-25](https://user-images.githubusercontent.com/18753171/51078163-76d1e380-16b1-11e9-91e3-9cd682b9f2f2.png)

**Comment by robertwolter** [comment]
Now I see the "problem": The package "xfce4-screenshooter-plugin" already 
contains the command "xfce4-screenshooter", so there is  no extra package for it.
![bildschirmfoto_2019-01-12_21-42-49](https://user-images.githubusercontent.com/18753171/51078306-5f93f580-16b3-11e9-90b8-153800de5125.png)

**Comment by robertwolter** [comment]
This is just different for Linux distros, which I'm used to, there always it the extra package "xfce4-screenshooter". So blame it on my Linux bias ;)

**Comment by robertwolter** [comment]
It's just a naming convention. So this issue can be closed.

**Comment by miwi-fbsd** [comment]
Great that this is sorted :). Welcome to the BSD world!
