### ISSUE TITLE
Missing man pages

### ISSUE THREAD

**Issue by pkgdemon** [trueos/trueos#48]
This may be limited to networking adapters.  

For some reason on the latest images things like:

```
man cxl
```

or

```
man cxgbe
```

are not found.

**Comment by kmoore134** [comment]
Ok, sure enough it looks like the manpages for those drivers aren't being installed properly as part of package base. They came in from distribution file before. My recent etcupdate work may fix this, but I'll have to get another build going to test.

**Comment by kmoore134** [comment]
scratch that. I checked our poudriere jail and its also missing those manpages, but that doesn't use pkg base...
