### ISSUE TITLE
trueos_base install, weird graphics on some computers (lenovo in particluar)

### ISSUE THREAD

**Issue by RodMyers** [trueos/trueos#67]
on computers, in particular lenovo thinkpads, during the install process. an  incorrect screen resolution is selected.

Having the ability to change the behaviour would be nice.

Maybe something, like was discussed. having the ability during the install process to edit the /boot/loader.rc.local file to set the gop.

**Comment by kmoore134** [comment]
This is mostly a documentation effort. The correct thing to do in this case is to figure out which GOP resolution works for your particular hardware. I've started some documentation on this here: https://github.com/trueos/trueos/wiki/UEFI-Resolution

We can work on cleaning it up and adding more examples as we go. Perhaps it can also host a list of known good resolutions for particular hardware.
