### ISSUE TITLE
separate pkg package in base

### ISSUE THREAD

**Issue by miwi-fbsd** [trueos/trueos#73]
after upgrading a base system from a lower version we see now 

``` pkg-static: Warning: Major OS version upgrade detected.  Running "pkg-static install -f pkg" recommended```

when we now have only base packages and run "pkg-static install -f pkg"  only we see,

```
# pkg-static install -f pkg
Updating TrueOS repository catalogue...
 Fetching meta.txz: 100%    820 B   0.8kB/s    00:01
 Fetching packagesite.txz: 100%   56 KiB  57.6kB/s    00:01
 Processing entries: 100%
 TrueOS repository update completed. 817 packages processed.
 All repositories are up to date.
 Updating database digests format: 100%
 pkg-static: No packages available to install matching 'pkg' have been found in the repositories
```

I think we will hit this issue soon as well when FreeBSD 12 is released and Current switch to 13.

**Comment by kmoore134** [comment]
Martin,

This is mostly cosmetic. Since we control the version of pkg we ship and only use 'pkg-static' for tools such as trueos-update I'm not as sure we need to split pkg out again.

**Comment by pkgdemon** [comment]
https://github.com/trueos/trueos/pull/75

**Comment by pkgdemon** [comment]
@kmoore134 or am I mistaken about the patch?

**Comment by kmoore134** [comment]
Yep, miwi fixed it via that other patch.
