### ISSUE TITLE
Request: Parallelize the "make packages" step

### ISSUE THREAD

**Issue by beanpole135** [trueos/trueos#91]
Currently, when running "make -jX packages", the "-jX" is getting ignored and the entire package routine occurs on a single CPU thread. 
This appears to be an oversight in the "packages" target in Makefile.inc1 (approximately line 1618), as all the other make targets include the use of an additional variable (${.MAKEFLAGS}) in the arguments when running the "${MAKE}" subcommand (see the "delete-old-files" target for an example: ~ line 2677).

**Comment by miwi-fbsd** [comment]
That must be set per poudriere.conf with ALLOW_MAKE_JOBS=yes, but u might see unexecpt failures.

**Comment by beanpole135** [comment]
no, this is when building the base packages, not when poudriere is running to compile ports.

**Comment by beanpole135** [comment]
Just for additional reference/context:
The "make packages" build stage is run after the kernel/world are compiled, and is the step where all the *.txz package files are assembled for the base package system.

Standard steps for building a distribution:
1. make buildworld
2. make buildkernel
3. make packages (base packages)
4. Startup poudriere for building ports
5. make release (assemble ISO's)

**Comment by darkfiberiru** [comment]
As a side note make release respects the J flag but.... blows up if J>1 some of the time and all the time as J gets even bigger. Need to be careful that if we implement this for make package that it is safe and does proper locking/queuing

**Comment by kmoore134** [comment]
This is something I don't think we can do right now, after a lot of playing with those Makefiles it's not designed for this.
