### ISSUE TITLE
Additional Ports optimizations out of box

### ISSUE THREAD

**Issue by beanpole135** [trueos/trueos#96]
After a conversation with miwi, there might be a few more classes of ports that we should add to the "ALLOW_MAKE_JOBS_PACKAGES" line in the auto-generated poudriere.conf.

Relevant File: release/release-trueos.sh (~line 92)
Packages to consider adding:
* py* (miwi)
* php* (miwi)
* p5-* (miwi)
* phantomjs* (beanpole135 - this hold up other ports for quite a while on iterative rebuilds)
* swift* (beanpole135 - this hold up other ports for quite a while on iterative rebuilds)

**Comment by miwi-fbsd** [comment]
in addional to py* for flavors.
